### PR TITLE
Fetch slugs with player data

### PR DESCRIPTION
**Pull request by mbjoseph**

### CODE REVIEW

**Comment by TaoJones** [comment]
Hi, I am trying to use this code (which is awesome!) but keep getting a message about package html2 not being available in version 3.4.0.  Any thoughts on how to get around this?  I've tried using the archived code to grab it from an older version, but still can't get it.  Thanks.

**Comment by mbjoseph** [comment]
Hi @TaoJones - do mean the xml2 package? I don't think there is a html2 package.

**Comment by TaoJones** [comment]
That's kind of what I thought, but when I try to create a data frame, I get this:
```
> a_data <- get_players("A")
Error in loadNamespace(name) : there is no package called ‘html2’
```

**Comment by TaoJones** [comment]
What does this part of the getplayers function represent?

`html <- html2::read_html(url)`

edit: you know what, I think that I must have accidentally edited that somehow, though I can't quite figure out why.  I see in the original post that it should be xml2, not html2.

**Comment by mbjoseph** [comment]
Yep - I think it's xml2: https://github.com/mbjoseph/bbr/blob/master/R/get_players.R#L33

Have you tried installing the xml2 library with devtools?:

```r
devtools::install_github("hadley/xml2")
```

**Pull request merged**
